format = """
${custom.prompt_char} $username@$hostname $directory $git_branch $kubernetes $time
$character
"""

add_newline = false

[character]
success_symbol = "[>>]() "
error_symbol = "[🎃💥>>](bold red) "

[custom.prompt_char]
when = "true"
command = "printf '%s\n' '🎃' ' 👻'| shuf -n1"
format = "[$output](bold white)"

# Username
[username]
show_always = true
style_user = "bold green"
format = "[$user]($style)"

# Hostname
[hostname]
ssh_only = false
style = "bold green"
format = "[@$hostname]($style) "

# Directory
[directory]
style = "bold blue"
truncate_to_repo = false
format = "[$path]($style) "

# --------------------------
# Git section
# --------------------------

[git_branch]
disabled = false
symbol = " "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_state]
disabled = true

[git_commit]
disabled = true

# --------------------------
# Kubernetes
# --------------------------

[kubernetes]
disabled = false
format = "[$context|$namespace](bold cyan) "

# --------------------------
# Time
# --------------------------

[time]
disabled = false
time_format = "%H:%M:%S"
style = "bold yellow"
format = "[$time]($style)"
